#!/usr/bin/Rscript

library(knitr)
#render_markdown(strict = FALSE)
# opts_chunk$set(fig.align='center', fig.pos="htpb", cache=FALSE, echo=TRUE,
# message=FALSE, autodep=TRUE, fig.path='figure/', fig.width=5,
# par=TRUE)
# 
#opts_chunk$set(warning=FALSE, message=FALSE, comment=NA, tidy=FALSE, 
#refresh=TRUE)
# 
# # verbose compile:
# opts_knit$set(progress = TRUE, verbose = TRUE)
opts_chunk$set(dev = 'pdf')
knit("metafolio.Rnw")
