// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ricker_v_t_fast
double ricker_v_t_fast(double spawners, double a, double b, double d, double v_t);
RcppExport SEXP metafolio_ricker_v_t_fast(SEXP spawnersSEXP, SEXP aSEXP, SEXP bSEXP, SEXP dSEXP, SEXP v_tSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    double spawners = Rcpp::as<double >(spawnersSEXP);
    double a = Rcpp::as<double >(aSEXP);
    double b = Rcpp::as<double >(bSEXP);
    double d = Rcpp::as<double >(dSEXP);
    double v_t = Rcpp::as<double >(v_tSEXP);
    double __result = ricker_v_t_fast(spawners, a, b, d, v_t);
    return Rcpp::wrap(__result);
END_RCPP
}
// thermal_curve_a_fast
double thermal_curve_a_fast(double temp, double optim_temp = 15, double max_a = 1.4, double width_param = 0.02);
RcppExport SEXP metafolio_thermal_curve_a_fast(SEXP tempSEXP, SEXP optim_tempSEXP, SEXP max_aSEXP, SEXP width_paramSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    double temp = Rcpp::as<double >(tempSEXP);
    double optim_temp = Rcpp::as<double >(optim_tempSEXP);
    double max_a = Rcpp::as<double >(max_aSEXP);
    double width_param = Rcpp::as<double >(width_paramSEXP);
    double __result = thermal_curve_a_fast(temp, optim_temp, max_a, width_param);
    return Rcpp::wrap(__result);
END_RCPP
}
