# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimate beta params
#'
est_beta_params <- function(mu, var) {
    .Call('metafolio_est_beta_params', PACKAGE = 'metafolio', mu, var)
}

#' Implementation error
#'
impl_error <- function(mu, sigma_impl) {
    .Call('metafolio_impl_error', PACKAGE = 'metafolio', mu, sigma_impl)
}

#' Ricker stock-recruit function with specified error
#'
ricker_v_t <- function(spawners, a, b, d, v_t) {
    .Call('metafolio_ricker_v_t', PACKAGE = 'metafolio', spawners, a, b, d, v_t)
}

#' Is element
#'
is_element <- function(x, y) {
    .Call('metafolio_is_element', PACKAGE = 'metafolio', x, y)
}

#' Super fast linear regression
#'
fastlm <- function(yr, Xr) {
    .Call('metafolio_fastlm', PACKAGE = 'metafolio', yr, Xr)
}

#' Fit Ricker linear regression
#'
fit_ricker <- function(S, R) {
    .Call('metafolio_fit_ricker', PACKAGE = 'metafolio', S, R)
}

#' Assign a salmon escapement target based on a Ricker curve
#'
ricker_escapement <- function(a, b) {
    .Call('metafolio_ricker_escapement', PACKAGE = 'metafolio', a, b)
}

#' Main Rcpp function
#'
#' @export
metasim_base <- function(n_pop, n_t, spawners_0, b, epsilon_mat, A_params, add_straying, stray_mat, assess_years, r_escp_goals) {
    .Call('metafolio_metasim_base', PACKAGE = 'metafolio', n_pop, n_t, spawners_0, b, epsilon_mat, A_params, add_straying, stray_mat, assess_years, r_escp_goals)
}

